CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL DEFAULT '', phone text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('admin','seller')), UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_role(_user_id uuid, _role text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles r JOIN public.profiles p ON p.id=r.user_id WHERE r.user_id=_user_id AND r.role=_role AND p.active); $$;
REVOKE ALL ON FUNCTION public.has_role(uuid,text) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.has_role(uuid,text) TO authenticated, service_role;
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY roles_read ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE FUNCTION public.create_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,email) VALUES(NEW.id,NEW.email); RETURN NEW; END; $$;
REVOKE ALL ON FUNCTION public.create_profile() FROM PUBLIC;
CREATE TRIGGER app_create_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_profile();
CREATE TABLE public.seller_permissions (user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE, search_hotels boolean NOT NULL DEFAULT true, search_flights boolean NOT NULL DEFAULT true, create_proposals boolean NOT NULL DEFAULT true, manage_transport boolean NOT NULL DEFAULT true);
GRANT SELECT ON public.seller_permissions TO authenticated; GRANT ALL ON public.seller_permissions TO service_role;
ALTER TABLE public.seller_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY permissions_read ON public.seller_permissions FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE TABLE public.system_settings (id integer PRIMARY KEY DEFAULT 1 CHECK(id=1), agency_name text NOT NULL DEFAULT 'Excursão Brasília', whatsapp text NOT NULL DEFAULT '5561992267062');
GRANT SELECT ON public.system_settings TO authenticated; GRANT ALL ON public.system_settings TO service_role;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY settings_read ON public.system_settings FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'seller'));
CREATE TABLE public.access_activity (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid NOT NULL, target_id uuid, action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.access_activity TO authenticated; GRANT ALL ON public.access_activity TO service_role;
ALTER TABLE public.access_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY activity_admin ON public.access_activity FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin'));
ALTER TABLE public.proposals ADD COLUMN owner_id uuid REFERENCES public.profiles(id);
CREATE INDEX proposals_owner_idx ON public.proposals(owner_id,created_at DESC);
CREATE FUNCTION public.seller_can(_permission text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_role(auth.uid(),'admin') OR EXISTS(SELECT 1 FROM public.seller_permissions s JOIN public.profiles p ON p.id=s.user_id WHERE s.user_id=auth.uid() AND p.active AND public.has_role(auth.uid(),'seller') AND CASE _permission WHEN 'search_hotels' THEN s.search_hotels WHEN 'search_flights' THEN s.search_flights WHEN 'create_proposals' THEN s.create_proposals WHEN 'manage_transport' THEN s.manage_transport ELSE false END); $$;
REVOKE ALL ON FUNCTION public.seller_can(text) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.seller_can(text) TO authenticated,service_role;
DROP POLICY "Qualquer um cria proposta" ON public.proposals;
DROP POLICY "Qualquer um lê proposta pelo código" ON public.proposals;
REVOKE ALL ON public.proposals FROM anon;
GRANT SELECT, INSERT ON public.proposals TO authenticated; GRANT ALL ON public.proposals TO service_role;
CREATE POLICY proposals_owner_read ON public.proposals FOR SELECT TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY proposals_owner_create ON public.proposals FOR INSERT TO authenticated WITH CHECK(owner_id=auth.uid() AND public.seller_can('create_proposals'));
CREATE FUNCTION public.public_proposal(_code text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT payload FROM public.proposals WHERE code=_code AND _code ~ '^[a-z0-9]{6,12}$'; $$;
REVOKE ALL ON FUNCTION public.public_proposal(text) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.public_proposal(text) TO anon, authenticated,service_role;