import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { ManagementNav } from "@/components/ManagementNav";
import { useAccess } from "@/components/AccessProvider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { listMyProposals } from "@/lib/settings.functions";
import { setProposalStatus } from "@/lib/proposals.functions";
import { decodeProposal, brl, packageTotal, nightsBetween } from "@/lib/hotels";
import { FileText, Send, CheckCircle2, Clock, Plus, ExternalLink, Pencil, Phone, UserRound, CalendarDays, MapPin, XCircle, Search, GripVertical, Loader2 } from "lucide-react";

const boardOptions = (id: string) => queryOptions({ queryKey: ["proposal-board", id], queryFn: () => listMyProposals(), refetchInterval: 30000 });
export const Route = createFileRoute("/_authenticated/vendedor")({
  validateSearch: (search: Record<string, unknown>) => ({ q: typeof search.q === "string" ? search.q : "" }),
  loader: async ({ context }) => { await context.queryClient.ensureQueryData(boardOptions(context.user.id)); },
  errorComponent: ({ error }) => <BoardError message={error.message} />,
  notFoundComponent: () => <BoardError message="Página não encontrada." />,
  head: () => ({ meta: [{ title: "Quadro de propostas — Excursão Brasília" }, { name: "description", content: "Acompanhamento das propostas de viagem e resultados da equipe." }, { property: "og:title", content: "Quadro de propostas — Excursão Brasília" }, { property: "og:description", content: "Propostas criadas, aguardando resposta e concluídas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }, { name: "robots", content: "noindex, nofollow" }] }),
  component: SellerPage,
});
function BoardError({ message }: { message: string }) { const router = useRouter(); return <div className="flex min-h-screen"><ManagementNav current="seller" /><main className="p-8"><p role="alert">{message}</p><Button onClick={() => router.invalidate()}>Tentar novamente</Button></main></div>; }
type Status = "created" | "awaiting" | "approved" | "cancelled";
const columns = [{ id: "created", title: "Propostas criadas", icon: FileText, tone: "text-primary", line: "border-primary" }, { id: "awaiting", title: "Aguardando resposta", icon: Clock, tone: "text-chart-1", line: "border-chart-1" }, { id: "closed", title: "Concluídas", icon: CheckCircle2, tone: "text-success-foreground", line: "border-success-foreground" }] as const;
const dateTime = (value: string) => new Date(value).toLocaleString("pt-BR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" });
const date = (value: string) => new Date(value + "T12:00").toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" });
function SellerPage() {
  const access = useAccess(); const { user } = Route.useRouteContext(); const { q } = Route.useSearch(); const navigate = Route.useNavigate();
  const { data: rows } = useSuspenseQuery(boardOptions(user.id)); const client = useQueryClient(); const changeStatus = useServerFn(setProposalStatus);
  const [pending, setPending] = useState<{ code: string; status: Status; client: string; phone?: string } | null>(null);
  const [dragged, setDragged] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: changeStatus, onSuccess: async () => { setPending(null); await client.invalidateQueries({ queryKey: ["proposal-board"] }); await client.invalidateQueries({ queryKey: ["settings"] }); } });
  const filtered = rows.filter(row => { const p = decodeProposal(row.payload); return `${p?.s.cliente ?? ""} ${p?.s.destino ?? ""} ${row.seller_name} ${row.code}`.toLowerCase().includes(q.toLowerCase()); });
  const request = (code: string, status: Status) => { const row = rows.find(r => r.code === code); if (!row) return; const s = decodeProposal(row.payload)?.s; mutation.reset(); setPending({ code, status, client: s?.cliente || "Cliente", ...(s?.telefone ? { phone: s.telefone } : {}) }); };
  return <div className="flex min-h-screen bg-background text-foreground"><ManagementNav current="seller" /><main className="min-w-0 flex-1 px-4 py-8 sm:px-7">
    <header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase text-muted-foreground">{access.admin ? "Visão geral da equipe" : "Meu espaço de vendas"}</p><h1 className="text-3xl font-bold">Propostas</h1><p className="mt-2 text-sm text-muted-foreground">{rows.length} propostas · {rows.filter(r => r.status === "awaiting").length} aguardando resposta</p></div><Button asChild><Link to="/pacotes" search={{}}><Plus />Nova proposta</Link></Button></header>
    <div className="mb-7 flex items-center gap-2 border-b border-border pb-5"><Search className="h-4 w-4 text-muted-foreground" /><Input aria-label="Buscar proposta" className="max-w-sm bg-card" placeholder="Cliente, destino ou vendedor" value={q} onChange={e => navigate({ search: { q: e.target.value }, replace: true })} /></div>
    <div className="grid grid-cols-1 items-start gap-5 xl:grid-cols-3">
      {columns.map(column => { const cards = filtered.filter(row => column.id === "closed" ? ["approved", "cancelled"].includes(row.status) : row.status === column.id); return <section key={column.id} aria-label={column.title} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragged) request(dragged, column.id === "closed" ? "approved" : column.id); setDragged(null); }} className="min-w-0">
        <div className={`mb-4 flex items-center justify-between border-t-2 ${column.line} pt-4`}><h2 className="flex items-center gap-2 text-sm font-semibold"><column.icon className={`h-4 w-4 ${column.tone}`} />{column.title}</h2><span className="grid h-6 min-w-6 place-items-center rounded-md bg-secondary px-1 text-xs font-semibold">{cards.length}</span></div>
        <div className="min-h-64 space-y-3">{cards.map(row => { const p = decodeProposal(row.payload); const s = p?.s; const minimum = p?.hotels.length ? Math.min(...p.hotels.map(h => packageTotal(h.total, s?.transport))) : null; return <article key={row.code} draggable onDragStart={() => setDragged(row.code)} onDragEnd={() => setDragged(null)} className="rounded-lg border border-border bg-card p-4 shadow-sm">
          <div className="mb-3 flex items-start justify-between gap-2"><div><p className="text-[11px] text-muted-foreground">#{row.code}</p><h3 className="mt-1 break-words font-semibold">{s?.cliente || "Cliente não informado"}</h3></div><GripVertical aria-label="Mover proposta" className="h-4 w-4 shrink-0 cursor-grab text-muted-foreground" /></div>
          {row.status !== "created" && <span className={`mb-3 inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold ${row.status === "approved" ? "bg-success text-success-foreground" : row.status === "cancelled" ? "bg-destructive/10 text-destructive" : "bg-secondary text-muted-foreground"}`}>{row.status === "approved" ? "Aprovada" : row.status === "cancelled" ? "Cancelada" : "Proposta enviada"}</span>}
          <div className="space-y-2 text-xs"><p className="flex items-start gap-2"><MapPin className="h-3.5 w-3.5 shrink-0 text-muted-foreground" /><span className="break-words">{s?.origem?.split(",")[0] || "Origem"} → {s?.destino?.split(",")[0] || "Destino"}</span></p>{s && <p className="flex items-center gap-2"><CalendarDays className="h-3.5 w-3.5 text-muted-foreground" />{date(s.checkin)} – {date(s.checkout)} · {nightsBetween(s.checkin, s.checkout)} noites</p>}<p className="break-words text-muted-foreground">{s?.hospedes || "Hóspedes não informados"}</p>{s?.telefone && <p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5 text-muted-foreground" />{s.telefone}</p>}{s?.email && <p className="break-all text-muted-foreground">{s.email}</p>}
          {p?.hotels.map((hotel, index) => <p key={index} className="break-words text-muted-foreground">{hotel.name}</p>)}{minimum !== null && <p className="pt-1 text-base font-bold">{p && p.hotels.length > 1 ? "A partir de " : ""}{brl(minimum)}</p>}</div>
          <div className="mt-4 space-y-2 border-t border-border pt-3 text-[11px] text-muted-foreground"><p className="flex items-start gap-2"><UserRound className="h-3.5 w-3.5 shrink-0" /><span className="break-all">{row.seller_name}</span></p><p>Criada em {dateTime(row.created_at)}</p>{row.sent_at && <p>Enviada em {dateTime(row.sent_at)}</p>}</div>
          <div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><a href={`/p/${row.code}`} target="_blank" rel="noreferrer"><ExternalLink />Abrir</a></Button><Button variant="ghost" size="sm" asChild><Link to="/pacotes" search={{ code: row.code }}><Pencil />Editar</Link></Button></div>
          <div className="mt-3 flex flex-wrap gap-2">{row.status === "created" && <Button size="sm" className="w-full" onClick={() => request(row.code, "awaiting")}><Send />Enviar proposta</Button>}{row.status === "awaiting" && <Button size="sm" variant="secondary" onClick={() => request(row.code, "approved")}><CheckCircle2 />Aprovar</Button>}{row.status !== "cancelled" && row.status !== "approved" && <Button size="sm" variant="ghost" onClick={() => request(row.code, "cancelled")}><XCircle />Cancelar</Button>}{["approved", "cancelled"].includes(row.status) && <Button size="sm" variant="ghost" onClick={() => request(row.code, "created")}>Reabrir</Button>}</div>
        </article>; })}{!cards.length && <div className="flex min-h-48 flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-border text-sm text-muted-foreground"><column.icon className="h-6 w-6" /><span>{q ? "Nenhum resultado" : "Nenhuma proposta"}</span></div>}</div>
      </section>; })}
    </div>
    <Dialog open={!!pending} onOpenChange={open => { if (!open && !mutation.isPending) setPending(null); }}><DialogContent><DialogHeader><DialogTitle>{pending?.status === "awaiting" ? "Enviar proposta" : pending?.status === "approved" ? "Confirmar aprovação" : pending?.status === "cancelled" ? "Cancelar proposta" : "Reabrir proposta"}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{pending?.client}</p>{pending?.status === "awaiting" && <div className="space-y-3"><Button variant="outline" className="w-full" onClick={() => { if (!pending) return; let phone = (pending.phone ?? "").replace(/\D/g, ""); if (phone.length === 10 || phone.length === 11) phone = `55${phone}`; const text = encodeURIComponent(`Olá! Sua proposta de viagem: ${window.location.origin}/p/${pending.code}`); window.open(`https://wa.me/${phone}?text=${text}`, "_blank", "noopener,noreferrer"); }}><Send />Abrir no WhatsApp</Button><Button variant="ghost" className="w-full" onClick={() => { if (pending) navigator.clipboard.writeText(`${window.location.origin}/p/${pending.code}`); }}>Copiar link</Button><p className="text-sm text-muted-foreground">O envio já foi realizado?</p></div>}{mutation.isError && <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p>}<DialogFooter><Button variant="outline" disabled={mutation.isPending} onClick={() => setPending(null)}>Voltar</Button><Button disabled={mutation.isPending || !pending} onClick={() => { if (pending) mutation.mutate({ data: { code: pending.code, status: pending.status } }); }}>{mutation.isPending && <Loader2 className="animate-spin" />}{pending?.status === "awaiting" ? "Confirmar envio" : "Confirmar"}</Button></DialogFooter></DialogContent></Dialog>
  </main></div>;
}
