/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as PCodeRouteImport } from './routes/p/$code'
import { Route as ApiPublicDestinationImageSlugRouteImport } from './routes/api/public/destination-image/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDestinationImageSlugRoute =
  ApiPublicDestinationImageSlugRouteImport.update({
    id: '/api/public/destination-image/$slug',
    path: '/api/public/destination-image/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proposta': typeof PropostaRoute
  '/p/$code': typeof PCodeRoute
  '/api/public/destination-image/$slug': typeof ApiPublicDestinationImageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proposta': typeof PropostaRoute
  '/p/$code': typeof PCodeRoute
  '/api/public/destination-image/$slug': typeof ApiPublicDestinationImageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proposta': typeof PropostaRoute
  '/p/$code': typeof PCodeRoute
  '/api/public/destination-image/$slug': typeof ApiPublicDestinationImageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/proposta' | '/p/$code' | '/api/public/destination-image/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proposta' | '/p/$code' | '/api/public/destination-image/$slug'
  id:
    | '__root__'
    | '/'
    | '/proposta'
    | '/p/$code'
    | '/api/public/destination-image/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropostaRoute: typeof PropostaRoute
  PCodeRoute: typeof PCodeRoute
  ApiPublicDestinationImageSlugRoute: typeof ApiPublicDestinationImageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/destination-image/$slug': {
      id: '/api/public/destination-image/$slug'
      path: '/api/public/destination-image/$slug'
      fullPath: '/api/public/destination-image/$slug'
      preLoaderRoute: typeof ApiPublicDestinationImageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropostaRoute: PropostaRoute,
  PCodeRoute: PCodeRoute,
  ApiPublicDestinationImageSlugRoute: ApiPublicDestinationImageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
